name: Build and Run Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build-and-run:
    runs-on: self-hosted
    name: Build and Run Docker Container
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to DockerHub or your container registry
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t my-golang-project:latest .

      # Stop and remove existing container if it exists
      - name: Stop and Remove Existing Container
        run: |
          if [ "$(docker ps -aq -f name=my-golang-container)" ]; then
            docker stop my-golang-container
            docker rm my-golang-container
          fi

      # Run the Docker container
      - name: Run Docker Container
        run: |
          docker run -d --name my-golang-container -p 8080:8080 my-golang-project:latest
