name: Build Docker Image

on:
  push:
    branches:
      - add-cicd-piepline
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: self-hosted
    name: Build Docker Image
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to DockerHub or your container registry
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t my-golang-project:latest .

      # Push the Docker image
      - name: Push Docker Image
        run: |
          docker tag my-golang-project:latest mujan/my-golang-project:latest
          docker push mujan/my-golang-project:latest
